version: '3.8'

services:
 script:
  build: .
  command: python /usr/src/app/main.py
  container_name: script-mtg
  depends_on:
    - db

 db:
  image: postgres:latest
  container_name: dbpg-mtg
  restart: always
  environment:
    POSTGRES_DB: data
    POSTGRES_USER: postgres
#    POSTGRES_PASSWORD: secret
#    POSTGRES_PORT: 5432
#  volumes:
#    - ./.database/postgres/data:/var/lib/postgresql/data
  ports:
    - "5435:5432"

#  adminer:
#      image: adminer
#      restart: always
#      depends_on:
#        - pgdb
#      ports:
#        - "8080:8080"
